### ISSUE TITLE
[c++] lambda parameters not highlighted properly

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#10]
```c++
auto glambda = [](auto a, auto&& b) { return a < b; };
```

(example from http://en.cppreference.com/w/cpp/language/lambda)

should highlight instances of `a` and `b` properly (differently at point of definition and use), but right now they are not.

**Comment by marijnh** [comment]
I think the issue was with the handling of `auto`, which I've improved in 5029a526fb69dd892. Could you see whether that solves the problem for you?

**Comment by mtaran-google** [comment]
yep, tried it now and it works well, thank you
