### ISSUE TITLE
[cc] would be better to highlight the whole of a namespaced type as a type when it's in type position

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#104]
for example, right now in this:

```cc
int main() {
  std::vector<int>::const_iterator iter = foo();
}
```

both `vector<int>` and `const_iterator` get highlighted as types, but the namespace `std` doesn't. But in the essentially similar

```cc
int main() {
  std::Foo::Bar bar = bar();
}
```
only `Bar` gets highlighted as a type.

I think the best solution that would make these cases consistent would be to highlight ~everything including namespaces as `type` when they're in a "type" position, e.g. describing the type of a variable or parameter.

**Comment by marijnh** [comment]
> I think the best solution that would make these cases consistent

Namespace prefixes are always highlighted as `meta`, and the final word is highlighted depending on the name's role. How is that not consistent?

**Comment by mtaran-google** [comment]
```cpp
int main() {
  std::vector<int>::iterator f;
  my::namespace::MyType::iterator g;
  my::namespace::MyType<int>::iterator h;
}
```

The current inconsistency is that for f, the last two segments are highlighted as types, for g only the last one is highlighted, and for h the last two again.

Since the naming conventions vary between e.g. the std namespace and Google's style (and sometimes the Google styleguide recommends sticking with STL conventions for consistency), it's not possible/desirable to try to guess whether a ::-separated segment is a namespace or a type name. We'd like the highlighting that you currently use for the last segment(s) to extend to the whole symbol (all of its ::-separated parts), since it's not possible in general to tell how many segments should be colored (per above).

**Comment by marijnh** [comment]
I see. Would you still like the `::` tokenized specially, or do those just become part of the identifier?

**Comment by mtaran-google** [comment]
CLion (which seems to follow roughly this highlighting strategy) leaves them as the default style, so perhaps something like that could work?

**Comment by marijnh** [comment]
See attached patch. I've added `qualifier` or `qualified` to the token types, depending on whether they play the role of qualifier or the final name. Does that work for you?

**Comment by mtaran-google** [comment]
Yes, I think that works. Thank you!
