### ISSUE TITLE
function invocations should not be highlighted (just) as `cm-builtin`

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#11]
Right now when functions are called, they are highlighted as `cm-builtin`. This isn't really accurate, and makes it impossible to e.g. use CSS to not highlight those (but still highlight builtins). It'd be great if either a different class was used, or another class was used together with `cm-builtin`.

**Comment by marijnh** [comment]
There's not really a style for this in existing CodeMirror themes. Would the using the class `variable callee` instead work for you?

**Comment by mtaran-google** [comment]
I think that would probably work
