### ISSUE TITLE
[cc] indentation of ternary expressions

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#111]
The indentation that clang-format produces for us looks like this: (from https://github.com/abseil/abseil-cpp/blob/master/absl/types/optional.h#L405)

```cpp
template <typename T>
constexpr copy_traits get_assign_copy_traits() {
  return std::is_copy_assignable<T>::value &&
                 std::is_copy_constructible<T>::value
             ? copy_traits::copyable
             : std::is_move_assignable<T>::value &&
                       std::is_move_constructible<T>::value
                   ? copy_traits::movable
                   : copy_traits::non_movable;
}
```

There are no explicit recommendations in the style guide about ternary operator indentation, but I hope it should not be too difficult to make it do this (do a continuing +4 indent based on the start of the last expression). The logic (from the clang-format developers) is that this makes the indentation more directly correspond to syntactic structure. Sorry for not having test cases/explicit guidance on this earlier.

**Comment by marijnh** [comment]
Why are the lines after the `&&` operators indented so deeply? That seems to be against the style guide (+4 for continued statements), and would impact how continuing lines are indented (i.e. +4 from the line before them would be a much deeper indent then shown in the example).

**Comment by mtaran-google** [comment]
Hmm. Let's leave this as is until I hear any specific complaints about it from people. Will close it for now and reopen in the future if anything comes up.
