### ISSUE TITLE
[cc] static_assert usage can confuse highlighting

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#118]
```cpp
template <typename T>
struct Foo {
  static_assert(compliant || std::is_trivially_destructible<T>::value,
                "Not compliant with std::is_trivially_destructible; "
                "Standard: false, Implementation: true");
  static_assert(compliant || !std::is_trivially_destructible<T>::value,
                "Not compliant with std::is_trivially_destructible; "
                "Standard: true, Implementation: false");
};
```

adapted from https://github.com/abseil/abseil-cpp/blob/master/absl/meta/type_traits.h#L149

the two usages of `static_assert` are highlighted different colors

**Comment by marijnh** [comment]
Those appear to be regular statements inside of a `struct` definition. I don't think that's valid C++ unless these are macros that expand to a struct field or nothing.

**Comment by mtaran** [comment]
from http://en.cppreference.com/w/cpp/language/static_assert

> A static assert declaration may appear at namespace and block scope (as a block declaration) and inside a class body (as a member declaration)

**Comment by marijnh** [comment]
Ah, right, it's part of the language. Recent C++ versions are becoming a scarily big language.
