### ISSUE TITLE
[cpp] Typing < can result in render failure in rawStringContinues.

### ISSUE THREAD

**Issue by takamori** [codemirror/google-modes#120]
In the C++ box, start typing the following after the enum declaration:
`static NoDestructor<g
`

The render will crash right after the `<` is entered inside of rawStringContinues here:
https://github.com/codemirror/google-modes/blob/master/src/cpp.js#L24

**Comment by marijnh** [comment]
Odd. I can't reproduce this, though -- if I open the current index.html and type that text below the enum, there's no error. Is there anything else that I need to do?

**Comment by takamori** [comment]
Interesting- I hadn't rerun `npm install`; after re-running that, it no longer repros, but my local git workspace only shows dist/java.js as having been modified.

I suspect the issue may have been fixed by some change in codemirror/grammar-mode v 0.1.3.

**Comment by marijnh** [comment]
Thanks, I could reproduce this now. It was a bug in codemirror-grammar-mode. I've just released version 0.1.4, which fixes it.
