### ISSUE TITLE
[cc] macro in class definition messes up indentation

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#122]
```cpp
class Foo {
  SOME_MACRO(Foo);
}
```
this is used in cases like https://github.com/google/or-tools/blob/master/ortools/sat/clause.h#L126

when you press enter after the `}`, you currently get an indent of +4, whereas it should be 0.

**Comment by marijnh** [comment]
The macro doesn't appear to have had anything to do with it, this happened for all empty lines after a class body. Attached patch should help.
