### ISSUE TITLE
[java] not enough indentation when using builder pattern

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#124]
```java
class Clazz {
  void foo() {
    return new Foo.newBlah(
        new Bar().)
  }
}
```
if you have the cursor after the last `.` and press enter, the cursor goes underneath the start of `new`, whereas it should have a +4 indent

**Comment by marijnh** [comment]
The builder pattern doesn't seem to a relevant factor here, this is how it indents any argument list. Do you want any continued expression to be indented extra? Or only specific types like `.`-access? I.e. should the third line be aligned with the start of the expression, or indented extra?

```
foo(
    1 + 3 +
    3 + 4)
```

**Comment by marijnh** [comment]
So a continued argument should always be intented more than the start of the argument? I.e. even in my example, you want the indentation shown below?

```
foo(
    1 + 3 +
        3 + 4)
```

**Comment by mtaran-google** [comment]
I checked with our formatter, and yes, that is correct.
