### ISSUE TITLE
[cc] Macro definitions can get unwanted syntax highlighting when comments are used

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#130]
```cc
#define FOO(/* some comment */...) \
   /* another comment */ \
   MyMacroIsGreat(__VA_ARGS__);
```

This should ideally all be gray, like other macro definitions. Alternatively, the comment could still be colored like a comment, but all the rest of the macro should be colored like other macros.

**Comment by marijnh** [comment]
Attached patch fixes this. But it does cause comments in preprocessor directives to get both the `comment` and the `meta` type, so you might have to adjust the order of your styles to get the coloring you want.
