### ISSUE TITLE
[java] Part of javadoc tokenized as "type"

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#139]
Looking at this snippet from ScheduledExecutorService.java in the JDK, a couple of the javadoc lines are tokenized as "type".
```java
package java.util.concurrent;

/**
 * ...
 *
 *  <pre> {@code
 * import static java.util.concurrent.TimeUnit.*;
 * class BeeperControl {
 *   private final ScheduledExecutorService scheduler =
 *     Executors.newScheduledThreadPool(1);
 *
 *   public void beepForAnHour() {
 *     final Runnable beeper = new Runnable() {
 *       public void run() { System.out.println("beep"); }
 *     };
 *     final ScheduledFuture<?> beeperHandle =
 *       scheduler.scheduleAtFixedRate(beeper, 10, 10, SECONDS);
 *     scheduler.schedule(new Runnable() {
 *       public void run() { beeperHandle.cancel(true); }
 *     }, 60 * 60, SECONDS);
 *   }
 * }}</pre>
 *
 * ...
 */
```

I guess GitHub's highlighting isn't ideal either.

**Comment by marijnh** [comment]
Is the problem that `@code` is supposed to suppress the normal meaning of braces inside it, and the mode doesn't support that?

**Comment by alur** [comment]
I don't think braces contain a type in javadoc, like they do in jsdoc. It looks like you're using the same grammar for both, even though they are somewhat different.

@param, @return, and etc. are slightly different in javadoc, in that they don't have the type:
https://docs.oracle.com/javase/9/docs/specs/doc-comment-spec.html#param

It would be nice to have support for @throws as well :)

Tags should be ignored within code blocks, though I'm not entirely clear on how it handles open and closing braces inside the @code block.
https://docs.oracle.com/javase/9/docs/specs/doc-comment-spec.html#code

**Comment by marijnh** [comment]
Ah, that makes sense. Implemented in attached patch.

**Comment by alur** [comment]
Couple of nits:
`@param` can reference a type parameter, like `@param <V>`, I think the V should get tokenized as a def here too.
The exception after `@throws` should be a type.
