### ISSUE TITLE
[py] local variables lose their def highlighting when the method declaration is scrolled out

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#148]
Repro:
- Create a python method with a fair amount of lines (I used a long docstring).
- Scroll down so the method declaration is outside the viewport.
- Do something that will cause a re-render (for me clicking on the corresponding line seems to do the trick).
- Notice that the def highlighting vanishes.

The def highlighting also blinks out and in when modifying the value the variable is assigned when defined.

```python
def bar(foo):
  """ A long comment block here.































  Args:
    foo: Foo
  """
  abc = 123

  return abc
```

On a related note, having a definition highlight is a little weird in python sometimes. In the following example, I'd argue each of the 3 assignments of x is as much a definition as the previous. Yet, only the first is highlight.

```python
def bar(foo):
  if foo == 'abc':
    x = 2
  elif foo == 'def':
    x = 3
  else:
    x = 4
  return x
```

**Comment by marijnh** [comment]
I wasn't able to reproduce the first issue—are you using a recent version of CodeMirror? Does it happen in the demo in this repository as well?

Regarding the second, yes, that's a little awkward but hard to avoid—we can either highlight all assignments to a variable or only the first, the mode isn't able to do advanced enough control flow analysis to determine which definitions might define the variable.

**Comment by alur** [comment]
Yeah, I'm using CodeMirror straight of HEAD. It repros for me with the sample content on the demo page.

Here "indent" has the highlight:
![3ocabqhxaof](https://user-images.githubusercontent.com/1925047/40385381-41b0209a-5dbb-11e8-9998-3bbafd5cda96.png)

And after scrolling down a bit and clicking on a line it's gone:
![vez1ycbbpv2](https://user-images.githubusercontent.com/1925047/40385382-41c35ea8-5dbb-11e8-81c4-a6daf2c8e119.png)

I'm running Chrome 66 on linux (though I'd be very surprised if this was system specific).

Regarding the second point, I meant to suggest that it would be better not to highlight defs for local variables in python. I really didn't expect you to be able to determine which assignments were defs :)

**Comment by marijnh** [comment]
Ah, I can see it now. Attached patch should help.

> Regarding the second point, I meant to suggest that it would be better not to highlight defs for local variables in python. I really didn't expect you to be able to determine which assignments were defs :)

Oh, right, you'd have to take that up with Maksym, he came up with this requirement.
