### ISSUE TITLE
[ts] Highlighting broken after indexed return type.

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#150]
```typescript
interface Bar {
  getOption<K extends keyof Config>(option: K): Config[K];
  foo(): void;
}
```

**Comment by marijnh** [comment]
I can't find this notation in the TypeScript spec, but that unfortunately not uncommon. Could you point me at some documentation for what this syntax means? Is the thing between brackets simply another type or are there additional subtleties?

**Comment by alur** [comment]
It was introduced in TS 2.1, I think the best description is in the release notes:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html

Apparently this is technically also valid (though I don't really see why...):
```typescript
interface Person {
    name: string;
    age: number;
    location: string;
}

function foo(p: Person): Person["name"]['length'] {
  return p.name.length;
}

function bar(p: Person): Person["name"] {
  return p.name;
}
```

**Comment by marijnh** [comment]
Ah, interesting. That was easy enough to implement, see bddde53
