### ISSUE TITLE
[go] too much indentation with for-range loop

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#156]
```go
func Bar(ch chan string) {
	for _, x := range []struct {
		foo string
	}{
		{
			foo: "bar", // Enter here should align with foo
		}, // Enter here should align with the closing } on this line
	} { // Enter here should align with ch
		ch <- x.foo // Enter here should align with ch
	} // Enter here should align with the closing } on this line
}
```

**Comment by marijnh** [comment]
I'm not sure I understand this code correctly. `[] struct { foo string }` is a type, I guess, and the braces after that wrap the loop body. What is `{foo: "bar"}` in the body? As far as I understand, braces in statement position open a new block, but this looks like it is intended to be an expression. And then there's another set of braces after the body—what does that mean?

**Comment by alur** [comment]
It's looping over an array of structs, with the entries defined right there. It might be more clear with more entries:
```go
func main() {
	for _, x := range []struct {
		foo string
	}{
		{
			foo: "bar",
		},
		{
			foo: "bar2",
		},
		{
			foo: "bar3",
		},
	} {
		fmt.Println(x.foo)
	}

	for _, y := range []int{2, 3, 5, 7} {
		fmt.Println(y)
	}
}
```
https://play.golang.org/p/dRm-CZIG6Sl

**Comment by marijnh** [comment]
Ahh, Go has a rather subtle ambiguity (see [here](https://golang.org/ref/spec#Composite_literals), near the end of that subsection) around composite literals and the braces around the bodies of `for` or `if` blocks. Attached patch improves the grammar's handling of that.
