### ISSUE TITLE
[go] variables declared before the ; in an if statement appear to leak out

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#16]
```go
func main() {
  if z := 1; z % 2 == 1 {
    i := 2;
  } else {
	z = 2;
  }
  fmt.Println(z)
}
```
the z in the else clause should be highlighted as a local, but not outside the if

**Comment by marijnh** [comment]
Fixed in attached patch, but do note that there's a limit to tracking variable scopes like this. For example, the complexities of JavaScript's scopes are not really something that I fully implement, and there's probably corner cases in other languages that the modes get wrong.

**Comment by mtaran-google** [comment]
Thanks. Indeed the craziness in JS with hoisting, temporal dead zones etc. is too much and is not something that I would expect the mode to deal with.
