### ISSUE TITLE
[py] assigment with an expression list breaks highlighting

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#164]
```python
x = 2, 3
print x
```

**Comment by marijnh** [comment]
I'm not seeing anything go wrong with this code. Can you be more specific?

**Comment by alur** [comment]
Maybe it's just the local variable highlighting.

```python
def either(foo, bar):
  x = foo
  return foo or bar

def both(foo, bar):
  x = foo, bar
  return foo and bar
```

After the expression list assignment variables stop being highlight as locals.

**Comment by marijnh** [comment]
Ah, right, I see it now. Attached patch should address this.
