### ISSUE TITLE
[js] closure-style @typedef tag's break highlighting

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#165]
Seems like you expect an identifier after @typedef, which I guess should be there for JSDoc, but we primarily use closure compiler annotations, which have the symbol name after the comment block.

https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#typedef-type

**Comment by marijnh** [comment]
So you'd prefer for the mode not to highlight the next identifier after the braces in tags like `@typedef` and `@param`, or only `@typedef`?

**Comment by alur** [comment]
Yeah, only @typedef.

Though I'd really prefer it being optional, which would be compatible with normal jsdoc as well. The main problem is that it misses the termination of the comment block and starts highlighting code as a comment.

![screen shot 2018-06-12 at 1 29 20 am](https://user-images.githubusercontent.com/1925047/41278963-136a7656-6de0-11e8-8fdf-2a4b8b6c637c.png)

The code from the screenshot:
```javascript
/**
 * @typedef {{
 *   constructor: (!Function|undefined),
 *   statics: (Object|undefined|function(Function):void)
 * }}
 */
goog.defineClass.ClassDescriptor;

goog.defineClass.isUnsealable_ = function(ctr) {
  return ctr && ctr.prototype &&
      ctr.prototype[goog.UNSEALABLE_CONSTRUCTOR_PROPERTY_];
};

/**
 * @define {boolean} Whether the instances returned by goog.defineClass should
 *     be sealed when possible.
 *
 * When sealing is disabled the constructor function will not be wrapped by
 * goog.defineClass, making it incompatible with ES6 class methods.
 */
goog.define('goog.defineClass.SEAL_CLASS_INSTANCES', goog.DEBUG);
```

**Comment by marijnh** [comment]
Ah, I see what you mean now. The def name was already optional, but I had messed something up in the way whitespace and asterisks before it were consumed, so that the `*` of the closing punctuation was accidentally consumed. Attached patch should fix that.
