### ISSUE TITLE
[java] missing closing brace in doc comments shouldn't extend past the end of the comment

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#171]
One of our users had a `@link` tag with a closing paren instead of a brace, which caused the rest of the file to be treated as the tag's attribute.

I suspect it's similar to the `@typedef` issue in jsdoc?

**Comment by marijnh** [comment]
I haven't been able to reproduce this—do you have a code sample? Just creating a comment like `/** {@link foo) */` doesn't seem to cause it.

**Comment by marijnh** [comment]
Oh, never mind, I found it (the `*/` had to follow a newline)
