### ISSUE TITLE
[ts] Assignment assertion breaks highlighting afterwards

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#176]
Sample from the TS 2.7 release notes:
```typescript
class C {
    foo!: number;
    // ^
    // Notice this '!' modifier.
    // This is the "definite assignment assertion"

    constructor() {
        this.initialize();
    }

    initialize() {
        this.foo = 0;
    }
}
```

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#definite-assignment-assertions

**Comment by alur** [comment]
This still repros. constructor and initialize are tokenized as variables rather than defs.

**Comment by marijnh** [comment]
Oh, right, I was reading the release notes and only noticed the variable declaration case—attached patch adds support on properties.
