### ISSUE TITLE
[ts] highlighting breaks on templated struct member

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#185]
```typescript
describe('Foo', () => {
  const foo = fooFunc<{
    spy: jasmine.SpyObj<Bar>,
    bar: Bar,
  }>();
});
```

**Comment by marijnh** [comment]
Are you sure type arguments can be provided to a plain (non-callee) value like that (jasmine.SpyObject)? Is there any reference for that syntax?

**Comment by alur** [comment]
This is a slight modification of some actual running test code.

Here's a link to a similar example in the TS playground
https://www.typescriptlang.org/play/#src=class%20Bar%20%7B%7D%0D%0Aclass%20Foo%3CT%3E%20%7B%7D%0D%0A%0D%0Afunction%20foo%3CT%3E()%20%7B%7D%0D%0A%0D%0Afoo%3C%7B%0D%0A%20%20x%3A%20Foo%3CBar%3E%2C%0D%0A%20%20y%3A%20number%2C%0D%0A%7D%3E()%3B

**Comment by marijnh** [comment]
Ah, right, apologies, I didn't see that this was in type position. The problem was that the mode didn't look ahead far enough and thus didn't disambiguate `fooFunc` as a function call. Attached patch adds another heuristic to address that.
