### ISSUE TITLE
[ts] wrong indentation when pressing enter on a very eagerly wrapped assignment line

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#186]
```ts
const foo = 
    new FooRequest()
```

if you press enter at the end of the last line, cursor goes to column 4, when it should go to column 8 since it's wrapping again

**Comment by marijnh** [comment]
That's not how the indentation currently works—it'll indent once per statement, not for every newline in the statement. I'm not quite sure how the behavior you are expecting would work.

**Comment by mtaran-google** [comment]
I think we'd discussed a similar issue in https://github.com/codemirror/google-modes/issues/124 (though we use one formatter for Java and a different one for C++/JS/TS). Both of the following are produced by the formatter depending on external constraints (e.g. how close the 80 column ruler is):

```ts
const foo = new Bar()
                .baz()
                .quux();

const foo =
    new Bar()
        .baz()
        .quux();
```

In both cases, the rule is that the wrapped element gets a +4 indent relative to the column that started the element at the same syntactic level. There are two such syntactic levels here, the outer one is the assignment statement and the inner one on the right is the `new...()` expression. Only one indent should be added inside the expression (as you said), but also one indent may be added when a line break occurs at the level of the statement, since in the second example the RHS expression hasn't started yet.

**Comment by marijnh** [comment]
This appears to be different from #124. I've added a special case for wrapped method calls under a `new` expression in attached patch.

But I want to make a note that this is the last extra indentation behavior I'm prepared to add. Of course I'll continue to respond to reports of obviously bad indentation, but given that no real requirements were provided for the indentation, and this is turning into 'the tool must do whatever some other tool happens to do', I can't keep adding new behavior (indentation is relatively tricky to get right, so this is turning into a bit of a time drain).
