### ISSUE TITLE
[cpp] pointer cast in if statement breaks indentation/highlighting

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#193]
```cpp
int main() {
  int x = 0;
  void *y = &x;
  if ((int *)y) {
    return 1;
  } else {
    return 0;
  }
}
```

if you press enter after the `return 1;` the indentation goes back to column 2 rather than staying at 4, and the highlighting turns off inside the if.

**Comment by marijnh** [comment]
It looks like patch dbd6f022defe78e took care of this as well.
