### ISSUE TITLE
[py] print statement breaks indentation

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#195]
```ts
class MyClass(object):
  def method1(self):
    print "foo"
```

Currently pressing enter after the "foo" indents to column 0, but should indent to 4.

The print statement is discouraged by the current styleguide, but can be found in older code. Since it can be used by itself, the sanest thing to do would be to just indent to the same level as the print was at. This shouldn't interfere with indentation of print as a function since having spaces between the function and its `(` is not allowed by the style guide.

**Comment by marijnh** [comment]
I remember you asking me to implement Python 3 (where `print` is a regular function). Did the requirements change to include Python 2?

**Comment by mtaran-google** [comment]
In our Jun 22, 2017 correspondence you'd asked

> Do you want me to implement Python 3 or Python 2?

and I replied:

> Ideally both (behind an option). Python 2 is the top priority though. The type annotations (PEP 484 and PEP 3107) are lower priority as well (and should be behind an option).

The function syntax is encouraged by the style guide in Python 2 as well, via `from __future__` imports, cf https://github.com/google/styleguide/blob/gh-pages/pyguide.md#from-__future__-imports

**Comment by marijnh** [comment]
Oh, right, attached patch makes the mode support either form.
