### ISSUE TITLE
[py] closing square bracket should be electric

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#197]
Right now only the } seems to be, which leads to an asymmetry in how multi-line objects and multi-line lists get indented. I think the same reasoning applies to ), both for when it's used to make a multi-line tuple and when it's being used for function application. I'm a little worried about the side-effects with doing this on ) in particula, but I think it's worth trying out to see if our users spot any issues.

**Comment by marijnh** [comment]
The current regexp is `/^\s*[\}\]\)]$/`, so I'm not sure where the asymmetry with `}` is coming from. Can you give a more concrete example?

**Comment by marijnh** [comment]
This isn't about electric behavior, but about the indentation the mode computes for that line (it aligns it with the numbers). Your indentation tests had a case like this:

```
meal = [
    spam,
    beans,
    ]
```

Hence this behavior. I agree that not great, so attached patch changes it to match your example from this issue. Let me know if you do want to preserve the old behavior.

**Comment by mtaran-google** [comment]
You're right about the test cases. My apologies, they were incorrect. They would only be correct for the case that there was no ] after the cursor when you pressed enter.

I think your patch should work well for the time being. I'm not sure how common the case is where people would want this to also apply for ). In my view it would be more common to have the current behavior for when you want to add an extra parameter, but we'll see if users complain.

Thank you!
