### ISSUE TITLE
[py] Code is highlighted incorrectly if a backslash precedes a docstring

### ISSUE THREAD

**Issue by takamori** [codemirror/google-modes#200]
Repros with the following code:

```py
_FOO = \
"""
Here is one line of text.
Another line of text

And another.
"""

class Bar(Baz):
    pass
```

After the backslash, the docstring text is highlighted like code, and the code is highlighted like a docstring.

Does not repro w/ the following:

```py
_FOO = "abc"
"""
Here is one line of text.
Another line of text

And another.
"""

class Bar(Baz):
    pass
```

Also does not repro in the standard CodeMirror Python mode.

**Comment by marijnh** [comment]
This was a bug in the grammar compiler. Attached patch upgrades that and resolves this.

**Comment by langner** [comment]
Thanks!
