### ISSUE TITLE
[py] seems like an infinite loop when adding a newline in the middle of a string

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#213]
```py
s = '\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000'
```

put the cursor right before the last \ and press enter -- the browser tab hangs

**Comment by marijnh** [comment]
I wasn't able to reproduce this. Does it happen in the index.html in this repository, if you replace the code in the Python demo with the string you gave?

**Comment by mtaran-google** [comment]
I was, but likely one of your other changes fixed this as well. Thanks!
