### ISSUE TITLE
[cc] Syntax highlighting broken after function-type template parameter.

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#223]
The example is a little contrived, but its based on actual code!

```c++
class Base {
 public:
  const int &GetValue() const { return x; }
  const int x = 3;
};

template <const int &(Base::*BaseValueProvider)() const>
class Foo {
 public:
  Foo() {}
  const int Val(Base &base) { return (base.*BaseValueProvider)(); }
};

int main() {
  Base base;
  Foo<&Base::GetValue> foo;
  return foo.Val(base);
}
```

**Comment by marijnh** [comment]
What does the `*` before `BaseValueProvider` do here? I can't find it in the grammar.

**Comment by alur** [comment]
I find cdecl.org useful for this stuff.

const int &(Base::*BaseValueProvider)() <-> declare BaseValueProvider as pointer to member of class Base function returning reference to const int

I don't think I had heard of pointers to members before seeing this.
https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.cbclx01/cplr034.htm

.* and ->* are special operators for using the pointer-to-member types.
https://en.cppreference.com/w/cpp/language/operator_member_access

**Comment by marijnh** [comment]
Wild. Attached patch adds support for these.
