### ISSUE TITLE
[cc] definition of variable in if condition messes up highlighting

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#227]
```cc
int main() {
  if (const auto* foo = bar()) {
    return 1;
  }
}
```

`const` should be highlighted as a keyword, but has no highlighting

cf https://stackoverflow.com/questions/12655284/defining-a-variable-in-the-condition-part-of-an-if-statement

**Comment by marijnh** [comment]
Ah, interesting. Attached patch adds support for this. There's a bit of an issue with conditionals like `a && b`, which are also valid declarations (but probably not meant as such in conditional context). I've added a kludge to disambiguate those—we'll see if more cases like that come up.
