### ISSUE TITLE
[cpp] matchbrackets is broken when -> is used.

### ISSUE THREAD

**Issue by takamori** [codemirror/google-modes#233]
If one uses the latest version of CodeMirror, this is broken. In the C++ example, navigate to "Class::Method2" and put the cursor at the end of the line (line 34). The curly brace incorrectly matches to the > in "value->Method3" instead of the end of method.

This likely broke after the following commit for vim which modified the matchbrackets addon:
https://github.com/codemirror/CodeMirror/commit/9376ad89daee45102e1a0a46a96d70d9ea8e9fd5

Interestingly, I notice it's not broken in https://codemirror.net/mode/clike/index.html
It's also not broken when google-modes dependencies is set to 5.42.0.

**Comment by marijnh** [comment]
This is a regression in matchbrackets.js, caused by https://github.com/codemirror/CodeMirror/commit/9376ad89d . Attached patch (in the CodeMirror repo) fixes it.

**Comment by marijnh** [comment]
Ah, right, I missed a case. Attached patch should help with that.
