### ISSUE TITLE
[java] making a local var of the same name as a method highlights incorrectly

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#247]
```java
class Foo {
  int status() {
    return 1;
  }
  
  void foo() {
    int status = status();
  }
}
```

the last usage of `status` should not highlight as a local variable usage since it's not (it's a usage of the method with the same name, and furthermore the local variable is not defined yet).

**Comment by marijnh** [comment]
That seems beyond what our simple scoping model can handle—it considers scopes to span entire syntax tree nodes (the method body in this case), and doesn't have a model of definition order, nor of namespaces (not too familiar with Java—would a use of the method _after_ the local has been defined still work?)

**Comment by mtaran-google** [comment]
Okay, that seems like a reasonable line to draw. 

> not too familiar with Java—would a use of the method after the local has been defined still work?

Yes, I agree it's pretty weird, but locals/fields and methods don't conflict since their usages can't be ambiguous. Fields/locals can't be called, and methods can only be called (or used in a method reference, but that's pretty distinct).
