### ISSUE TITLE
[cc] Highlighting breaks after a function specialization template

### ISSUE THREAD

**Issue by takamori** [codemirror/google-modes#250]
Repros for C++ with the following code. Highlighting breaks after the "template int Foo" line.

```cpp
template <typename T>
T Foo(T t) {
  return t;
}

template int Foo<int>(int t);

void NextMethod() {}

int OtherMethos(const string& unused_s) { return 5; }
```

**Comment by marijnh** [comment]
I don't think I'll ever stop being surprised by C++ syntax (couldn't find this construct in [this grammar](http://www.nongnu.org/hcb/) either). But as far as I understand what's going on, attached patch adds support for this.
