### ISSUE TITLE
[ng-template] tag autocompletion addon in codemirror doesn't trigger

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#266]
the closetag.js addon doesn't work in the angular template mode (or in the html mode etc.)

**Comment by marijnh** [comment]
That's true. It relies on state information specific to the XML mode in the main distribution, which isn't used by the ng-template mode.

Attached patches (one in codemirror, two in this repo) try to make that state inspection more abstract. Could you see if they work for you?

**Comment by mtaran-google** [comment]
(was on vacation earlier) Indeed these two things fix the issue. Thanks!
