### ISSUE TITLE
[cpp] incorrect parse of "using Bar = struct {};" syntax.

### ISSUE THREAD

**Issue by takamori** [codemirror/google-modes#272]
Repros with:

```cpp
namespace {
  struct Foo {
    using Bar = struct {};
    using Baz = struct {};
  }
}
```

**Comment by marijnh** [comment]
So the thing after `=` in `using` is a type, right? I am unable to find the grammar rule that allows braces to appear after `struct` in a type. Can you point me at something that describes this?

**Comment by takamori** [comment]
While I didn't write the associated code, I believe `Bar` and `Baz` above would be type aliases for an empty struct.

I believe the parse tree would be as follows (references hyperlinked):

[**alias-declaration:** `using` identifier `=` type-id;](https://www.nongnu.org/hcb/#alias-declaration)
[**type-id:** type-specifier-seq](https://www.nongnu.org/hcb/#type-id)
[**type-specifier-seq:** type-specifier](https://www.nongnu.org/hcb/#type-specifier-seq)
[**type-specifier:** class-specifier](https://www.nongnu.org/hcb/#type-specifier)
[**class-specifier:** class-head `{ }`](https://www.nongnu.org/hcb/#class-specifier)
[**class-head:** class-key](https://www.nongnu.org/hcb/#class-head)
[**class-key:** `struct`](https://www.nongnu.org/hcb/#class-key)

**Comment by marijnh** [comment]
Ah yes, I guess that makes sense. Attached patch should help.
