### ISSUE TITLE
[ts] support optional chaining operator

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#283]
Typescript 3.7 added a new "?." operator, which currently breaks syntax highlighting.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html

**Comment by alur** [comment]
I noticed you already had a commit for this (https://github.com/codemirror/google-modes/commit/5d7f6d2632bc5ee45b608ac5c0fa5e7cbb4908af), but it doesn't seem to work.

Even for something simple like
```ts
const x = z?.a;
let y = 2;
```

**Comment by marijnh** [comment]
My bad, I added it to the JS mode (since it's also about to become standard there), but didn't notice that the TypeScript mode overrode the rule that it occurred in, so it wasn't working there yet. Attached patch fixes that.
