### ISSUE TITLE
[cpp] unexpected indent after variadic args separated by a comma.

### ISSUE THREAD

**Issue by takamori** [codemirror/google-modes#290]
syntax ref: https://en.cppreference.com/w/cpp/language/variadic_arguments

```cpp
static void error(State* state, const char* msg);
// following line indents ok

static void error2(State* state, const char* msg...);
// also indents ok

static void error3(State* state, const char* msg...);
                   // unexpected indent.
```

**Comment by marijnh** [comment]
I'm unable to reproduce this with the example code—there may be a mistake in that code because the definitions for `error2` and `error3` are exactly equivalent, so unless the error was somehow triggered only after two repetitions of the syntax, that seems suspicious.

**Comment by takamori** [comment]
sorry, I had a typo there; I was missing a comma in the last example after doing some editing/copy/paste:

```cpp
static void error(State* state, const char* msg);
// following line indents ok

static void error2(State* state, const char* msg...);
// also indents ok

static void error3(State* state, const char* msg, ...);
                   // unexpected indent.
```

**Comment by marijnh** [comment]
Ah, that helps.
