### ISSUE TITLE
[feature request] hosted demo.html page somewhere?

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#294]
It's really useful having the online codemirror demos on codemirror.net. We often send our users to it to repro issues in order to confirm if they're on our end or CodeMirror's. Do you think it would be possible to set up something like that for the google-modes demo html page? Using github pages, or even a not-advertised page on codemirror.net would work well...

**Comment by marijnh** [comment]
I've set up https://codemirror.net/google-modes/ for this.

**Comment by takamori** [comment]
thanks!!
