### ISSUE TITLE
[cpp] Unqualified function lacks syntax highlighting

### ISSUE THREAD

**Issue by takamori** [codemirror/google-modes#299]
```cpp
bool (*Foo)(const std::string& host) = bar::Baz;  // unhighlighted
extern bool (*Foo)(const std::string& host) = bar::Baz;  // highlighted
```

**Comment by marijnh** [comment]
This was falling out of C++'s ambiguous grammar. Up until `const` this line might well be an expression, so the parser decides that it probably is, and parses it as such. I've added another lookahead rule to handle this case.
