### ISSUE TITLE
runmode issues with linebreaks

### ISSUE THREAD

**Issue by alur** [codemirror/google-modes#300]
```js
const node = document.createElement('div');

// Marks const as a variable
CodeMirror.runMode(`void Foo(
    const std::shared_ptr<Bar>&)`, 'google-c', node)

// Marks const as a keyword
CodeMirror.runMode(`void Foo(const std::shared_ptr<Bar>&)`, 'google-c', node)
```
I don't see the same issue in an actual codemirror.

**Comment by marijnh** [comment]
`runMode` didn't have support for across-line lookahead yet, which these modes use a lot. Attached patch should address that.

**Comment by ngzhian** [comment]
While trying to upgrade chrome devtools frontend, I encountered
https://github.com/codemirror/CodeMirror/commit/0884405eb7f0903af0b0b074a07343f8ed680ac7 
which changed the signature for CodeMirror.StringStream.

There is a slightly different signature in https://github.com/codemirror/CodeMirror/blob/master/src/util/StringStream.js#L9 .

Is this intended difference intended?

**Comment by marijnh** [comment]
I assumed the `StringStream` implementation was private to runmode-standalone, but I see it's exported. Though I'm not sure how/why anyone would use it in external code. Are you?

**Comment by ngzhian** [comment]
The runmode-standalone implementation is used [here](https://osscs.corp.google.com/chromium/chromium/src/+/master:third_party/devtools-frontend/src/front_end/formatter_worker/FormatterWorker.js;l=57?q=stringstream&ss=chromium%2Fchromium%2Fsrc:third_party%2Fdevtools-frontend%2Fsrc%2F) in side a worker that does formatting.

In other places, [like this](https://osscs.corp.google.com/chromium/chromium/src/+/master:third_party/devtools-frontend/src/front_end/third_party/codemirror/package/src/line/highlight.js;l=144?q=stringstream&ss=chromium%2Fchromium%2Fsrc:third_party%2Fdevtools-frontend%2Fsrc%2F) we use the util/StringStream.js implementation.

+tvanderlippe@ who knows more about this

**Comment by marijnh** [comment]
I can't access the code, but it seems likely that you only load the standalone version to use `runMode`, and use `StringStream`'s constructor in a situation where the whole editor is loaded.

Still, it'd make sense to keep these interfaces compatible, I guess. See attached patch.

**Comment by ngzhian** [comment]
Oh sorry my bad, updated links to point to source.chromium.org links, which will be accessible.
