### ISSUE TITLE
[py] f-string support

### ISSUE THREAD

**Issue by superbobry** [codemirror/google-modes#301]
Currently, f-string literals are lexed as a single token

https://github.com/codemirror/google-modes/blob/42086ba8e9e9cf88d46be8d738273294d170f6a5/src/python.grammar#L175-L178

Wdyt about changing the lexer to break the f-string into placeholders and lex/parse each placeholder as an expression? so that CodeMirror could highlight the corresponding expressions, e.g.

```python
f"The value of {x}*{x} is {(lambda x: x**2)(x)}"
``` 

(GitHub syntax highlighter seems to already support that)

**Comment by marijnh** [comment]
That'd be a good idea. I expect it could work similar to the way template strings are parsed in the JS mode.

**Comment by superbobry** [comment]
Would you accept a PR for that? or would you rather implement it yourself? :)

**Comment by marijnh** [comment]
A PR would be wonderful.
