### ISSUE TITLE
[py] f-strings seem to affect auto-indentation

### ISSUE THREAD

**Issue by superbobry** [codemirror/google-modes#304]
Reproducer:

```python
def f():
  ("foo" f"bar")
```

Hitting ENTER after `)` will move the cursor to column 0. 

I had a quick look at `findIndent` and it seems that if the thing preceding the cursor is an f-string, the context is `null`. Do you have any pointers on what could be causing this?

**Comment by marijnh** [comment]
The problem might be that the Python grammar doesn't support multiple strings in a row yet, and the auto-recovery just happens to mess up the parsing more for f-strings than for regular stings because of their more complicated structure.

**Comment by superbobry** [comment]
I think it does

https://github.com/codemirror/google-modes/blob/91289120d452265a26140e9e091791562ce79f3d/src/python.grammar#L66-L67

Note also that the issue only affects f-strings, i.e. ENTER in

```
def f():
  ("foo" "bar")
```

works as expected.
