### ISSUE TITLE
[cpp] operator overloading syntax breaks highlighting

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#316]
```cpp
inline bool Cord::ChunkIterator::operator==(const ChunkIterator& other) const {
  return bytes_remaining_ == other.bytes_remaining_;
}
```

from [here](https://github.com/abseil/abseil-cpp/blob/d3614de6178018178723ac3b8b4baaf3f1dc7fcb/absl/strings/cord.h#L1092)

the `const ChunkIterator& other` isn't highlighted

**Comment by marijnh** [comment]
Attached patch should help with this.
