### ISSUE TITLE
[kt] Kotlin 1.4 support: minimally fun interfaces appear broken

### ISSUE THREAD

**Issue by kevin1e100** [codemirror/google-modes#320]
[Kotlin 1.4](https://kotlinlang.org/docs/reference/whatsnew14.html) introduces a few features that may affect parsing/syntax highlighting, notably:

* `fun interface` declarations: these currently look broken, apparently because codemirror expects a function declaration after the `fun` keyword.  Instead, `fun` should be treated as a modifier here (while leaving function declarations unchanged).
* trailing commas affect function declarations and invocations, but seem to already be tolerated/handled
* type annotations may affect parsing of types, including function types, e.g., `fun foo(init: @Bar Baz.(@Bar Foo)->String): @Bar String`

**Comment by mtaran-google** [comment]
@marijnh do you think you would be able to help with this?

**Comment by marijnh** [comment]
Sure. Attached patch adds support for `fun interface` (as I understand it from your explanation, not being a Kotlin programmer myself). The grammar seems to already allow annotations in front of types. If that doesn't cover your 3rd point, please elaborate.

**Comment by kevin1e100** [comment]
The `fun interface` patch looks right to me: `fun` immediately precedes `interface` for this case, IIUC, and there can be modifiers incl. annotations preceding, e.g., `@Foo public @Bar fun interface Baz`.

Agree that type annotations appear to be working: I get the expected highlighting using them in functions, type parameters, and type arguments.

Thanks so much for your quick help with this!
