### ISSUE TITLE
Kotlin formatting fails on `suspend` and `tailrec` function modifiers

### ISSUE THREAD

**Issue by jasperavisser** [codemirror/google-modes#327]
Here's an example with `suspend`. The exact same thing happens for `tailrec`. Both of these are function modifier keywords:
https://kotlinlang.org/docs/reference/keyword-reference.html#modifier-keywords

I haven't tested all the keywords; these are just the 2 that I ran into.

```kotlin
open class TrivialMath {
  fun add(a: Int, b: Int): Int = a + b
  suspend fun add(a: Int, b: Int): Int = a + b
  open fun add(a: Int, b: Int): Int = a + b
  open suspend fun add(a: Int, b: Int): Int = a + b
}
```

This formats as:
![image](https://user-images.githubusercontent.com/935599/104653365-c5f4e980-56ba-11eb-99a4-b7e14585f305.png)

Hope that helps!

**Comment by marijnh** [comment]
`tailrec` was misspelled in the grammar, I've fixed that in 24d0034.

I don't see `suspend` in https://kotlinlang.org/docs/reference/grammar.html#functionModifier — the grammar only lists `suspend` as a type modifier. Is that a mistake in that grammar, or am I missing something?

**Comment by jasperavisser** [comment]
Strange, I _do_  see it there ...

![image](https://user-images.githubusercontent.com/935599/104716831-b9a77580-5728-11eb-8bbd-bfd9b4f2d64c.png)

**Comment by marijnh** [comment]
Okay, not sure what my brain was doing there (I was convinced I had ctrl-f-ed the page for 'suspend' and only hit the type keyword... but indeed, it's right there). Attached patch adds it to the grammar.

**Comment by jasperavisser** [comment]
Much obliged, Marijn! Thanks for the quick responses! 😄
