### ISSUE TITLE
[kt] Newline sometimes has the incorrect tab indentation

### ISSUE THREAD

**Issue by lwuk** [codemirror/google-modes#331]
With some code like: 
```kotlin
class SampleClient {

  fun doSomething() {
    listof("foo","bar")
      .map { it.length }
  }
[newline]
}
```

the line with `[newline]` is expected to have one more level of indentation than it does after returning from the previous line.

Removing the line `.map { it.length }` seems to make the issue go away.

**Comment by marijnh** [comment]
The way I seem to have understood Kotlin at the time I wrote the grammar is that you can't have a newline between an expression and a "." access, because such a newline will end the statement. Is this incorrect?

**Comment by lwuk** [comment]
Yep, you can break accesses with newlines and it's smart enough to know where the expression ends.

**Comment by marijnh** [comment]
I see. Attached patch should help with this.
