### ISSUE TITLE
[cc] const auto* const not highlighting well

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#334]
```cpp
const auto* const foo = GetFoo();
```

should highlight the `const`s as keywords but only the first one gets correctly highlighted

**Comment by mtaran-google** [comment]
friendly ping? :)

**Comment by marijnh** [comment]
Ah, sorry, lost track of this one.  Attached patch should address it.

**Comment by mtaran-google** [comment]
Thanks! :)
