### ISSUE TITLE
Build issue with Vite

### ISSUE THREAD

**Issue by TJKoury** [codemirror/google-modes#341]
Built the repo per the directions, getting this error:

`Object prototype may only be an Object or null: undefined`

Using the flatbuffers.js, version 1.0.0 of this repo, at line 444:

    `FlatBuffersMode.prototype = Object.create( superclass && superclass.prototype );`

**Comment by marijnh** [comment]
I don't know what flatbuffers is, but it's not a dependency of this repository, so I don't see how this report belongs here.

**Comment by TJKoury** [comment]
[Right here](https://github.com/codemirror/google-modes/blob/master/dist/flatbuffers.js), it’s a mode in this library.

**Comment by marijnh** [comment]
Hah, I see, that was contributed at some point. Well, it looks like the value being passed in there comes from the `CodeMirror` global, and the problem is probably that you're not loading CodeMirror and/or `codemirror-grammar-mode/src/mode.js` in your page.
