### ISSUE TITLE
[java] While typing a method invocation, it's initially highlighted as a type

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#4]
e.g. while you're typing `foo();` (inside a method), until you type the `(` the text is highlighted as a type. But it shouldn't be, since types should be considered to start from an uppercase letter except for the builtin raw types. `f` and `fo` and `foo` should never be highlighted as types.

**Comment by marijnh** [comment]
The way I understand it, casing is just convention in Java, and it's possible to declare classes with lowercase names. Is it really important enough to not color this as a type during typing to encode a constraint that the language doesn't have into the mode?

**Comment by mtaran-google** [comment]
The whole point of our style guide is to provide additional constraints and to make code more standardized and easily readable. So adding this constraint into the mode is very desirable.
