### ISSUE TITLE
[js] indentation for incomplete variable declaration (missing semicolon)

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#48]
```js
const x = new Foo()|
```

expected: indent of 4 when pressing enter at |, since it's not a finished statement (no semicolon, which is mandatory by the style guide)

actual: indent of 0

**Comment by marijnh** [comment]
I've implemented automatic semicolon insertion in my grammar. Do you want me to rip that out again?

**Comment by mtaran-google** [comment]
Yes, I think that would work best for us. Per the style guide: https://google.github.io/styleguide/jsguide.html#formatting-semicolons-are-required "Relying on automatic semicolon insertion is forbidden."

**Comment by marijnh** [comment]
I added an option for it instead, defaulted to no-automatic-insertion for now, but since the standard mandates automatic insertion, if you're okay with setting this on your side, I'd prefer to flip the default.
