### ISSUE TITLE
bad interaction with comment-continuation addon

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#58]
e.g. add the comment continuation addon, and pass in config `continueComments: {key: 'Enter', continueLineComment: false},`
in go:
```go
func f() {
	g(/* a */ 1) // b
}
```
press enter after b

expected: nothing special

actual: a * gets inserted

btw, since we use many of the standard addons, would you mind if I sent a PR adding those script imports and passing in a fuller config, to more closely replicate the setup that we are using these modes in?

**Comment by marijnh** [comment]
> actual: a * gets inserted

This is configured by the `blockCommentContinue` setting on the mode, and is how the continueComment addon works for the old modes as well. If you set it to three spaces you won't get that star. Shall I make that change for all the included modes?

> would you mind if I sent a PR adding those script imports and passing in a fuller config, to more closely replicate the setup that we are using these modes in?

Not at all.

**Comment by mtaran-google** [comment]
I don't think I understand what you're saying. We use this same configuration with our current (CodeMirror-standard) modes, and this issue's behavior does not occur. We *do* want the addon to properly continue block comments with a `*`, but only when the cursor & newline happen in a real block comment context. It seems like here the addon is just not understanding that it's in a line comment context, and that the block comment has already been closed.

**Comment by marijnh** [comment]
Ah, I see what you mean now. Though I could also reproduce the issue with the regular JavaScript mode. It appears to have been a bug in continuecomment.js, which I've fixed in attached patch. Does that help?

**Comment by mtaran-google** [comment]
yep, works great now. Thanks :)
