### ISSUE TITLE
[c++] templated class definition not highlighted properly

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#6]
```c++
template <class T, class V>
class Class : public BaseClass {
  const MyType<T, V> member_;
}
```

`template`, `class`, and `Class` aren't highlighted, but they should be

**Comment by marijnh** [comment]
I added this as a test in aba541a, and did run into an indentation issue, but the tokens you mention appear to be highlighted properly. Does the code maybe follow something else in your test, with the confusion coming from there?

**Comment by mtaran-google** [comment]
looks good now for me too. will open separate issues
