### ISSUE TITLE
[go] top-level var creation not highlighted right

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#62]
```go
var imported = map[string]bool{}
```

**Comment by marijnh** [comment]
That's highlighted the same as a local. What does an expression like this mean? I can't find it in the spec -- `map[keytype]valuetype` syntax seems to only be allowed as a type. Is this some kind of initializer expression? Do you know where it is described in https://golang.org/ref/spec ?

**Comment by mtaran-google** [comment]
Yep, https://golang.org/ref/spec#Composite_literals

**Comment by marijnh** [comment]
Ah, gotcha. See attached patch.
