### ISSUE TITLE
[cpp] C-style struct usages get highlighted wrong

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#67]
e.g.
```cpp
struct student_college_detail
{
    int college_id;
    char college_name[50];
};
 
struct student_detail 
{
    int id;
    char name[20];
    float percentage;
    // structure within structure
    struct student_college_detail clg_data;
}stu_data;
```
from http://fresh2refresh.com/c-programming/c-nested-structure/

**Comment by marijnh** [comment]
Attached patch fixes the highlighting of the `clg_data` field. Is that what you meant?

**Comment by mtaran-google** [comment]
Ideally, `student_college_detail` should also be highlighted as a type, since it's specifying the type of the `clg_data` field.

**Comment by marijnh** [comment]
Ah, I thought I had taken care of that but indeed, it's still wrong. Attached patch helps.
