### ISSUE TITLE
[c++] TEST macros can mess up indentation

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#77]
These are a staple of our C++ testing, though they're not explicitly documented in the style guide per se.

There are plenty of examples of their use in the absl codebase, e.g. https://github.com/abseil/abseil-cpp/blob/master/absl/strings/ascii_test.cc

Some issues currently:
```cc
TEST(ATest, Move) {
  int foo;
```
pressing enter after the semicolon takes you to column 0 whereas it should take you to column 2
variable declaration of foo is not highlighted

**Comment by marijnh** [comment]
Hm, that's tricky. It's ambiguous with a braced init list (which can appear after any expression). The problem with preprocessor macros is of course that they can do just about anything to the syntax, and a grammar-driven highlighter is going to have a bad time making sense of the result.

Do you want me to special-case this macro? Or maybe always parse braces after a function call as a block? Or are there similar cases where the macro doesn't look like a call?

**Comment by mtaran-google** [comment]
If special-casing, then I recommend expanding it to anything that's [A-Z_]*, since there are some less common variations of this macro. Always parsing braces after a function call as a block could work too. I don't believe we have similar cases where the macro doesn't look like a call.

**Comment by marijnh** [comment]
I've implemented the second solution (parse braces after calls as blocks) in attached patch. Let me know if you run into any further issues.
