### ISSUE TITLE
[cpp] raw strings defined using char[] are not tokenized properly.

### ISSUE THREAD

**Issue by takamori** [codemirror/google-modes#86]
The following is sufficient to repro the impact of this issue:

```
char raw_string[] = R"(
I said, "Hello //Hi" to the fish.
)";
int number = 2;
```

Note that the // makes the grammar ignore the other " and that the "Hello" is tokenized as a variable.

The same issue does not occur at http://codemirror.net/mode/clike/index.html

**Comment by marijnh** [comment]
The problem was caused by the `[]` after the declarator name. Attached patch should help.
