### ISSUE TITLE
[all] need either options or extra css classes/tokens to allow for configuration of local variable highlighting

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#92]
It turns out different people want to highlight/not highlight local variables. I think it would be ideal to support three alternatives in the end.

1. The current two-color scheme (coloring local var/parameter defs one way, and usages another).
2. A one-color scheme (coloring local var/parameter defs and usages the same way, e.g. how usages are colored in option 1 above).
3. Don't color local vars or usages in any particular way.

Currently it's not possible to enforce this with e.g. additional CSS rules because `def` is used for many other types of definitions. One option would be to use `def` + whatever other token it makes sense for it to have, e.g. `type` for class definitions, maybe `variable` for vars and constants, etc. The other option would be if this setting could just be set in the mode configuration, and it would change what styles it outputted.

Do you have a preference?

**Comment by marijnh** [comment]
What is stopping you from styling `variable-2` the same as `variable` when the user doesn't want to see local variables?

Since type definitions are already distinct (`"type def"`), coloring variable definitions with CSS also doesn't seem hard.

**Comment by mtaran-google** [comment]
Indeed type definitions are distinct, but `def` is currently also being applied to global, field and method definitions/declarations. Per the contract, the intent was to request was for distinct (or at least distinguishable, for future customization) highlighting of locals/parameters. I realize I included the same highlighting symbol for fields and locals in the provided test cases, for which I apologize.

**Comment by marijnh** [comment]
So you're asking for a way to style global variable/function definitions, local definitions, and field definitions differently? Would `"def local"` for locals and `"def property"` for field and properties work?

**Comment by mtaran-google** [comment]
Yes, and yes. :)

**Comment by marijnh** [comment]
Attached patches should take care of this.

**Comment by mtaran-google** [comment]
Thank you, yes, I think this should work well.
