### ISSUE TITLE
[all] the class/struct name in class/struct definitions should be colored like a type

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#93]
Looking at Visual Studio, IntelliJ and Eclipse, this appears to be the more common highlighting.

**Comment by marijnh** [comment]
I've made the changes in the attached patch, but I want to add that I'm not going to continue implementing new requirements endlessly, after the fact.

**Comment by mtaran-google** [comment]
Thank you for the change.

And I understand your concern, but I believe something to this effect was well within the scope of the contract. Before this change, it was not possible to distinguish class/interface/type names from local variable/template definitions and usages, which were two distinct things that the contract had requested highlighting for.
