### ISSUE TITLE
[cc] switches with static fields aren't handled well

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/google-modes#95]
```cpp
string foo(Bar s) {
  switch (s) {
    case Bar::OK: return "OK";
    case Bar::NotOk: return "NOT OK";
  }
}
```

**Comment by marijnh** [comment]
Please define "not handled well". The highlighting looks correct, when I paste this into the demo.

**Comment by mtaran-google** [comment]
sorry, I should have clarified: `case` gets labeled as `type`, which is incorrect

**Comment by marijnh** [comment]
Ahh, you're right. The rules were in the wrong order and this was parsed as a declaration. Attached patch fixes that.
